import { VoucherRecord } from "./types";

export const SEED_VOUCHER_RECORDS: VoucherRecord[] = [
  {
    "id": "seeded-1002",
    "serialNo": "25/120061",
    "date": "02/12/2025",
    "unitVrNo": "185/25",
    "payee": "M P C S YAKKALAMULLA",
    "description": "FUEL",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U15 - GALLE",
    "voucherAmount": 11960,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "Approved",
    "voucherAmountSec": 11960,
    "totalScheduleValue": 11960,
    "chequeValue": 11960,
    "crossEntry": 0,
    "totalPaid": 11960,
    "handOverDateToItmis": "11,960.00",
    "itmisEvNo": "45,994.00",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1003",
    "serialNo": "25/120062",
    "date": "02/12/2025",
    "unitVrNo": "184/25",
    "payee": "M P C S TANGALLE",
    "description": "FUEL",
    "vote": "225-1-1-0-1409-139- Vehicle Insurance",
    "unit": "U15 - GALLE",
    "voucherAmount": 1595,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "Fuel Type not Approved, Incomplete",
    "voucherAmountSec": 1595,
    "totalScheduleValue": 1595,
    "chequeValue": 1595,
    "crossEntry": 0,
    "totalPaid": 1595,
    "handOverDateToItmis": "1,595.00",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1004",
    "serialNo": "25/120063",
    "date": "02/12/2025",
    "unitVrNo": "183/25",
    "payee": "M P C S TANGALLE",
    "description": "FUEL",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U15 - GALLE",
    "voucherAmount": 1176,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "Approved",
    "voucherAmountSec": 1176,
    "totalScheduleValue": 1176,
    "chequeValue": 1176,
    "crossEntry": 0,
    "totalPaid": 1176,
    "handOverDateToItmis": "1,176.00",
    "itmisEvNo": "45,994.00",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1005",
    "serialNo": "25/120064",
    "date": "02/12/2025",
    "unitVrNo": "123/25",
    "payee": "M H M FAZUL HUQ",
    "description": "FUEL",
    "vote": "225-1-1-0 1001-Salaries and Wages",
    "unit": "ASP OFFICE - NORTH CENTRAL",
    "voucherAmount": 11760,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "Approved",
    "voucherAmountSec": 11760,
    "totalScheduleValue": 11760,
    "chequeValue": 11760,
    "crossEntry": 0,
    "totalPaid": 11760,
    "handOverDateToItmis": "11,760.00",
    "itmisEvNo": "45,994.00",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1006",
    "serialNo": "25/120065",
    "date": "02/12/2025",
    "unitVrNo": "124/25",
    "payee": "M PC S KARACHCHI SOUTH",
    "description": "FUEL",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "ASP OFFICE - NORTH CENTRAL",
    "voucherAmount": 8526,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "Approved",
    "voucherAmountSec": 8526,
    "totalScheduleValue": 8526,
    "chequeValue": 8526,
    "crossEntry": 0,
    "totalPaid": 8526,
    "handOverDateToItmis": "8,526.00",
    "itmisEvNo": "45,994.00",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1007",
    "serialNo": "25/120094",
    "date": "02/12/2025",
    "unitVrNo": "187/25",
    "payee": "S H M JAFRISH",
    "description": "FUEL",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U47 - PUTTALAM",
    "voucherAmount": 38514,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "-",
    "voucherAmountSec": 38514,
    "totalScheduleValue": 38514,
    "chequeValue": 38489,
    "crossEntry": 25,
    "totalPaid": 38514,
    "handOverDateToItmis": "38,514.00",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1008",
    "serialNo": "25/120095",
    "date": "02/12/2025",
    "unitVrNo": "193/25",
    "payee": "S H M JAFRISH",
    "description": "FUEL",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U47 - PUTTALAM",
    "voucherAmount": 50274,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "-",
    "voucherAmountSec": 50274,
    "totalScheduleValue": 50274,
    "chequeValue": 50249,
    "crossEntry": 25,
    "totalPaid": 50274,
    "handOverDateToItmis": "50,274.00",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1009",
    "serialNo": "25/120116",
    "date": "02/12/2025",
    "unitVrNo": "91/25",
    "payee": "LANKA FILING STATION",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U37 - MATHUGAMA",
    "voucherAmount": 45276,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "-",
    "voucherAmountSec": 45276,
    "totalScheduleValue": 45276,
    "chequeValue": 45251,
    "crossEntry": 25,
    "totalPaid": 45276,
    "handOverDateToItmis": "45,276.00",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1010",
    "serialNo": "25/120117",
    "date": "02/12/2025",
    "unitVrNo": "71/25",
    "payee": "KATUWANA ENTRAPRIS",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U20 - HOMAGAMA",
    "voucherAmount": 35868,
    "handOverDateToSubject": "25-12-02",
    "statusOfVr": "-",
    "voucherAmountSec": 35868,
    "totalScheduleValue": 35868,
    "chequeValue": 35843,
    "crossEntry": 25,
    "totalPaid": 35868,
    "handOverDateToItmis": "35,868.00",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1021",
    "serialNo": "25/120118",
    "date": "03/12/2025",
    "unitVrNo": "-",
    "payee": "DIG PSB",
    "description": "HIWEY TRAWAL",
    "vote": "225-1-1-0-1409-140 OTHER SERWIS",
    "unit": "H  Q",
    "voucherAmount": 800,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1022",
    "serialNo": "25/120129",
    "date": "03/12/2025",
    "unitVrNo": "198/25",
    "payee": "M P C S EMBILIPITIYA",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U48 - RATHNAPURA",
    "voucherAmount": 3528,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1023",
    "serialNo": "25/120130",
    "date": "03/12/2025",
    "unitVrNo": "189/25",
    "payee": "M P C S RATHNAPURA",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U48 - RATHNAPURA",
    "voucherAmount": 10913,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1024",
    "serialNo": "25/120131",
    "date": "03/12/2025",
    "unitVrNo": "98/25",
    "payee": "M P C S KABITHIGOLLAWA",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U22 - KEBITIGOLLEWA",
    "voucherAmount": 38808,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1025",
    "serialNo": "25/120132",
    "date": "03/12/2025",
    "unitVrNo": "161/25",
    "payee": "RANGIRI DAMBULLA",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U12 - DAMBULLA",
    "voucherAmount": 11466,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1026",
    "serialNo": "25/120133",
    "date": "03/12/2025",
    "unitVrNo": "-",
    "payee": "DIG PSB",
    "description": "O T D D N P JAYARATHNA NOV",
    "vote": "225-1-1-0 1002-Overtime and Holiday Payments",
    "unit": "HEAD QUARTERS",
    "voucherAmount": 33916,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1027",
    "serialNo": "25/120134",
    "date": "03/12/2025",
    "unitVrNo": "-",
    "payee": "DIG PSB",
    "description": "O TK K S SAMARASEKARA NOV",
    "vote": "225-1-1-0 1002-Overtime and Holiday Payments",
    "unit": "HEAD QUARTERS",
    "voucherAmount": 33118,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1028",
    "serialNo": "25/120135",
    "date": "03/12/2025",
    "unitVrNo": "-",
    "payee": "DIG PSB",
    "description": "O T D P L T SAMARAWEER NOV",
    "vote": "225-1-1-0 1002-Overtime and Holiday Payments",
    "unit": "HEAD QUARTERS",
    "voucherAmount": 28448,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1029",
    "serialNo": "25/120136",
    "date": "03/12/2025",
    "unitVrNo": "-",
    "payee": "DIG PSB",
    "description": "O T D P P WIKKRAMA",
    "vote": "225-1-1-0 1002-Overtime and Holiday Payments",
    "unit": "HEAD QUARTERS",
    "voucherAmount": 45528,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1030",
    "serialNo": "25/120137",
    "date": "03/12/2025",
    "unitVrNo": "160/25",
    "payee": "H D M HATHWALLAGE",
    "description": "SERVICE BJE 3647",
    "vote": "225-1-1-0-1301-Maintenance Vehicles",
    "unit": "U12 - DAMBULLA",
    "voucherAmount": 6430,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1031",
    "serialNo": "25/120138",
    "date": "03/12/2025",
    "unitVrNo": "139/25",
    "payee": "AJITH SERVICE CENTER",
    "description": "SERVICE ABV 1489",
    "vote": "225-1-1-0-1301-Maintenance Vehicles",
    "unit": "U33 - MANKULAM",
    "voucherAmount": 9200,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1032",
    "serialNo": "25/120139",
    "date": "03/12/2025",
    "unitVrNo": "101/25",
    "payee": "ISHARA MOTORS",
    "description": "SERVICE BBD 6325",
    "vote": "225-1-1-0-1301-Maintenance Vehicles",
    "unit": "U04 - AVISSAWELLA",
    "voucherAmount": 4700,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1033",
    "serialNo": "25/120140",
    "date": "03/12/2025",
    "unitVrNo": "100/25",
    "payee": "FAMOUS BAKE HOUSE",
    "description": "NEWSPEPAR BILL25 NOV",
    "vote": "225-1-1-0-1205-Other (Miscellaneous)",
    "unit": "U04 - AVISSAWELLA",
    "voucherAmount": 2100,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1034",
    "serialNo": "25/120141",
    "date": "03/12/2025",
    "unitVrNo": "140/25",
    "payee": "CLEANCO LANKA",
    "description": "ECO TEST",
    "vote": "225-1-1-0-1409-140- Other Services Expenses",
    "unit": "U33 - MANKULAM",
    "voucherAmount": 640,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1035",
    "serialNo": "25/120142",
    "date": "03/12/2025",
    "unitVrNo": "162/25",
    "payee": "OIC PSB DAMBULLA",
    "description": "PETTY CASH",
    "vote": "225-1-1-0-1205-Other (Miscellaneous)",
    "unit": "U12 - DAMBULLA",
    "voucherAmount": 5000,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1036",
    "serialNo": "25/120143",
    "date": "03/12/2025",
    "unitVrNo": "103/25",
    "payee": "OIC PSB AVISSAWELLA",
    "description": "PETTY CASH",
    "vote": "225-1-1-0-1205-Other (Miscellaneous)",
    "unit": "U04 - AVISSAWELLA",
    "voucherAmount": 5000,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1037",
    "serialNo": "25/120144",
    "date": "03/12/2025",
    "unitVrNo": "138/25",
    "payee": "SRI LANKA DIALOG",
    "description": "VPN BILL 25 OCT",
    "vote": "225-1-1-0-1402-Postal and Telecommunication",
    "unit": "U33 - MANKULAM",
    "voucherAmount": 12013.95,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1038",
    "serialNo": "25/120145",
    "date": "03/12/2025",
    "unitVrNo": "167/25",
    "payee": "URBAN DEVELOPMENT AUTHORITY",
    "description": "WATER BILL 09/15 TO 10/15",
    "vote": "225-1-1-0-1403-Electricity & Water",
    "unit": "U10 - COLOMBO NORTH",
    "voucherAmount": 1486.8,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1039",
    "serialNo": "25/120146",
    "date": "03/12/2025",
    "unitVrNo": "168/25",
    "payee": "URBAN DEVELOPMENT AUTHORITY",
    "description": "WATER BILL 09/15 TO 10/16",
    "vote": "225-1-1-0-1403-Electricity & Water",
    "unit": "U10 - COLOMBO NORTH",
    "voucherAmount": 5392.6,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1040",
    "serialNo": "25/120147",
    "date": "03/12/2025",
    "unitVrNo": "168/25",
    "payee": "ROVENGO ENTERPRISES",
    "description": "NEWSPEPAR BILL25 NOV",
    "vote": "225-1-1-0-1205-Other (Miscellaneous)",
    "unit": "U43 - NUGEGODA",
    "voucherAmount": 2400,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1041",
    "serialNo": "25/120148",
    "date": "03/12/2025",
    "unitVrNo": "123/25",
    "payee": "A N M L K R KUMARI NWARATHNA",
    "description": "NEWSPEPAR BILL25 NOV",
    "vote": "225-1-1-0-1205-Other (Miscellaneous)",
    "unit": "U45 - PANADURA",
    "voucherAmount": 1910,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1042",
    "serialNo": "25/120149",
    "date": "03/12/2025",
    "unitVrNo": "02/25",
    "payee": "A S P OFFICE SOUTHERN",
    "description": "PETTY CASH",
    "vote": "225-1-1-0-1205-Other (Miscellaneous)",
    "unit": "ASP OFFICE - SOUTHERN",
    "voucherAmount": 3500,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1043",
    "serialNo": "25/120150",
    "date": "03/12/2025",
    "unitVrNo": "124/25",
    "payee": "RIVEKA SERVICS",
    "description": "FULE",
    "vote": "225-1-1-0-1202-009 Pool Vehicle Fuel & Lubricant",
    "unit": "U45 - PANADURA",
    "voucherAmount": 12936,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  },
  {
    "id": "seeded-1044",
    "serialNo": "25/120151",
    "date": "03/12/2025",
    "unitVrNo": "-",
    "payee": "OIC PSB (P C 90153)",
    "description": "2025 NOVEMBER FOOD AND LORDGING",
    "vote": "225-1-1-0-1203-022-Food And Lordging Allowance",
    "unit": "U28 - KEGALLE",
    "voucherAmount": 8400,
    "handOverDateToSubject": "25-12-03",
    "statusOfVr": "-",
    "voucherAmountSec": 0,
    "totalScheduleValue": 0,
    "chequeValue": 0,
    "crossEntry": 0,
    "totalPaid": 0,
    "handOverDateToItmis": "-",
    "itmisEvNo": "-",
    "statusOfPmt": "-",
    "paidDate": "-",
    "scheduleNo": "-",
    "chequeNo": "-",
    "handoverTo": "-",
    "handOverDate": "-",
    "paidVrStatus": "-",
    "receivedDate": "-"
  }
];
